name: ci

permissions:
  contents: read

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:

  mpich-43:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      mpiname: mpich
      version:

  mpich-42:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      mpiname: mpich
      version: 4.2.3

  mpich-41:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      mpiname: mpich
      version: 4.1.3

  mpich-40:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      mpiname: mpich
      version: 4.0.3

  mpich-34:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      mpiname: mpich
      version: 3.4.3

  openmpi-50:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      mpiname: openmpi
      version:

  openmpi-41:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      mpiname: openmpi
      version: 4.1.7

  wheelhouse:
    runs-on: ubuntu-latest
    needs:
      - mpich-43
      - mpich-42
      - mpich-41
      - mpich-40
      - mpich-34
      - openmpi-50
      - openmpi-41
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: wheelhouse
        pattern: wheel-*
        merge-multiple: true
    - run: |
        # sha256sum
        echo '```'         >> "$GITHUB_STEP_SUMMARY"
        sha256sum -b *.whl >> "$GITHUB_STEP_SUMMARY"
        echo '```'         >> "$GITHUB_STEP_SUMMARY"
      working-directory: wheelhouse
    - uses: actions/upload-artifact@v4
      with:
        name: wheelhouse
        path: wheelhouse/*.whl
        retention-days: 1
