name: ci

permissions:
  contents: read

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      mpich:
        description: 'mpich'
        required: false
        type: boolean
        default: true
      openmpi:
        description: 'openmpi'
        required: false
        type: boolean
        default: true
      os-arch:
        description: 'os-arch'
        required: false
        type: choice
        default: '*'
        options:
          - '*'
          - Linux
          - Linux-aarch64
          - Linux-x86_64
          - macOS
          - macOS-arm64
          - macOS-x86_64
  pull_request:
    branches:
      - master

jobs:

  lint:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v6
    - run: pipx run tox

  mpich-43:
    if: ${{ github.event_name == 'pull_request' || inputs.mpich }}
    uses: ./.github/workflows/cd-wheel.yml
    with:
      os-arch: ${{ inputs.os-arch }}
      mpiname: mpich
      version:

  mpich-42:
    if: ${{ github.event_name == 'pull_request' || inputs.mpich }}
    uses: ./.github/workflows/cd-wheel.yml
    with:
      os-arch: ${{ inputs.os-arch }}
      mpiname: mpich
      version: 4.2.3

  mpich-41:
    if: ${{ github.event_name == 'pull_request' || inputs.mpich }}
    uses: ./.github/workflows/cd-wheel.yml
    with:
      os-arch: ${{ inputs.os-arch }}
      mpiname: mpich
      version: 4.1.3

  mpich-40:
    if: ${{ github.event_name == 'pull_request' || inputs.mpich }}
    uses: ./.github/workflows/cd-wheel.yml
    with:
      os-arch: ${{ inputs.os-arch }}
      mpiname: mpich
      version: 4.0.3

  mpich-34:
    if: ${{ github.event_name == 'pull_request' || inputs.mpich }}
    uses: ./.github/workflows/cd-wheel.yml
    with:
      os-arch: ${{ inputs.os-arch }}
      mpiname: mpich
      version: 3.4.3

  openmpi-50:
    if: ${{ github.event_name == 'pull_request' || inputs.openmpi }}
    uses: ./.github/workflows/cd-wheel.yml
    with:
      os-arch: ${{ inputs.os-arch }}
      mpiname: openmpi
      version:

  openmpi-41:
    if: ${{ github.event_name == 'pull_request' || inputs.openmpi }}
    uses: ./.github/workflows/cd-wheel.yml
    with:
      os-arch: ${{ inputs.os-arch }}
      mpiname: openmpi
      version: 4.1.7

  wheelhouse:
    if: >-
      github.event_name == 'pull_request'
      || (always() && (inputs.mpich || inputs.openmpi))
    runs-on: ubuntu-latest
    needs:
      - mpich-43
      - mpich-42
      - mpich-41
      - mpich-40
      - mpich-34
      - openmpi-50
      - openmpi-41
    steps:
    - uses: step-security/harden-runner@v2
      with:
        egress-policy: audit
    - uses: actions/download-artifact@v5
      with:
        path: wheelhouse
        pattern: wheel-*
        merge-multiple: true
    - run: |
        # sha256sum
        echo '```'         >> "$GITHUB_STEP_SUMMARY"
        sha256sum -b *.whl >> "$GITHUB_STEP_SUMMARY"
        echo '```'         >> "$GITHUB_STEP_SUMMARY"
      working-directory: wheelhouse
    - uses: actions/upload-artifact@v4
      with:
        name: wheelhouse
        path: wheelhouse/*.whl
        retention-days: 1
